---
title: "Covid-19 Dashboard "
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(plotly)
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"
myData <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") %>%   dplyr::select(Date = dateRep,Year = year ,Cases = cases, Deaths = deaths, Country = countriesAndTerritories)



CountryWiseData <- myData %>% 
                   group_by(Country) %>%
                   summarise(Confirmed_Cases = sum(Cases), Total_Deaths = sum(Deaths))%>%
                   mutate(Active_Cases = (Confirmed_Cases - Total_Deaths), 
                          Death_rate = (Total_Deaths / Confirmed_Cases)*100)

```



Visualization
=======================================================================
Row {data-height=150}
-----------------------------------------------------------------------

### confirmed cases

```{r}

valueBox(value = paste(myData %>%   
          dplyr::select(Cases = Cases) %>% sum()),
          color = confirmed_color)
```

### active cases

```{r}

valueBox(value = paste(myData %>%   dplyr::select(Cases = Cases) %>% 
           sum() -  myData %>%   dplyr::select(Deaths = Deaths) %>% sum()),
           color = active_color)
```


### Total deaths

```{r}
valueBox(value = paste(myData %>%   dplyr::select(Deaths = Deaths) %>% sum()),
         color = death_color)
```


Row {data-height=400}
-----------------------------------------------------------------------
### Total cases by type {.no-padding}

```{r}
plotly::plot_ly(data = CountryWiseData[1:50,], x = ~ Country, 
                y = ~Confirmed_Cases,
                text = ~Country,
                type = "bar",
                name = "Confirmed cases",
                marker = list(color = confirmed_color))%>%
plotly::add_trace(y = ~Active_Cases,
                name = "Total Active Cases",
                marker = list(color = active_color))%>%
plotly::add_trace(y = ~Total_Deaths,
                    name = "Total Deaths",
                    marker = list(color = death_color))%>%
plotly::layout(barmode = 'stack',
               yaxis = list(title = "Total Cases", type = "log"),
               xaxis = list(title = "CountryName"),
               hovermode = "compare",
               margin = list(
                 b = 10,
                 t = 10,
                 pad = 2
               ))


```






Row 
-----------------------------------------------------------------------

### Death rate by countryName {.no-padding}

```{r}
plotly::plot_ly(CountryWiseData[1:150,], x = ~Country, 
                y = ~ Death_rate,
                type = 'scatter', 
                mode = 'line+markers')%>%
      layout(title = "CountryWise Death Rate", annotations=~Death_rate)


```

### CountryWise Summary {.no-padding}
```{r}

CountryWiseData[1:nrow(CountryWiseData),0:4] %>%
  DT::datatable(rownames = FALSE,escape = FALSE,
                colnames = c("Country", "Confirmed Case","Total Deaths", "Active Cases"),
                options = list(pageLength = nrow(CountryWiseData),scrollX = TRUE, scrollY=TRUE, autoWidth=TRUE, dom = 't',order = list(1, desc),
                                columnDefs = list( list(targets=c(0), visible=TRUE, width='10%')),initComplete = JS("function(settings, json) {",
                "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
                "}")))

```

Map
=======================================================================

Data
=======================================================================
### Covid-19 All Country Data
```{r}
#these libraries need to be loaded
library(utils)
library(dplyr)
#read the Dataset sheet into “R”. The dataset will be called "data".

read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") %>%   dplyr::select(Date = dateRep,Year = year ,Cases = cases, Deaths = deaths, Country = countriesAndTerritories ) %>%
   DT::datatable(rownames = TRUE, caption = 'This Data Update Automatically Every day',
            options = list(searchHighlight = TRUE, 
                           pageLength = 20,
                initComplete = JS("function(settings, json) {",
                "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
                "}")))
```

About Me 
=======================================================================
```{r}
death <- myData %>% group_by(Country) %>% summarise(sumby = sum(Deaths))%>% filter(Country == 'India')
DT::datatable(death)
```